### ISSUE TITLE
Presentation slides

### ISSUE THREAD

**Issue by rukku** [microsat-dpad/git-demo#1]
Hi @benjiao, can you push a copy of your presentation slides? Or at least a link to it. Thanks!

**Comment by benjiao** [comment]
@rukku Oo nga pala. Done. May kulang pala ako sa workshop. dapat "merge/pull request" tayo instead of manually merging to master. Turo ko nalang kapag mag memerge na ng something sina @lululelu at @McGuillisKim.

**Comment by rukku** [comment]
:+1:
